# Generated by Django 3.2.4 on 2021-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageentry',
            old_name='main_colors',
            new_name='main_color',
        ),
        migrations.AddField(
            model_name='imageentry',
            name='size',
            field=models.CharField(choices=[('Large', '大'), ('Medium', '中'), ('Small', '小')], default='Small', max_length=20),
        ),
    ]
